app <- ShinyDriver$new("../../")
app$snapshotInit("mytest")

app$setInputs(size = 9)
app$setInputs(size = 8)
app$setInputs(size = 7)
app$snapshot()
app$snapshot()
app$setInputs(size = 16)
app$snapshot()
app$setInputs(size = 18)
app$snapshot()
